<div class="alert alert-block alert-danger">
<h2>Table of Contents</h2>
</div>

[Import Libraries](#1.0)<br>
[Connect to the mysql database](#2.0)<br>
[Load Data](#3.0)<br>
[Dataframes to SQL](#4.0)<br>
[Send the main dataframe replaced with index values](#5.0)<br>
[Add comments into sql tables](#6.0)<br>
[Add comments into columns in a sql table](#7.0)<br>

<a id='1.0'></a>
<div class="alert alert-block alert-danger">
<h2>Import Libraries</h2>
</div>

In [1]:
import warnings
warnings.filterwarnings('ignore')

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'    # ignore information messages

import math
import numpy as np 
import pandas as pd
# display all of the columns
pd.set_option('display.max_columns', None)

<a id='2.0'></a>
<div class="alert alert-block alert-danger">
<h2>Connect to the mysql database</h2>
</div>

<div class="alert alert-block alert-warning">
        Read the cvc file with username and password
</div>

In [2]:
mysql_user_pass = pd.read_csv('../../../mysql_user_pass.csv', index_col=0)
username = mysql_user_pass['mysql_user'][0]
password = mysql_user_pass['mysql_pass'][0]

<div class="alert alert-block alert-warning">
        Create an engine to connect to the mysql database
</div>

In [3]:
from sqlalchemy import create_engine

engine = create_engine(f'mysql+pymysql://{username}:{password}@localhost:3306/developer_survey_2020')

<a id='3.0'></a>
<div class="alert alert-block alert-danger">
<h2>Load Data</h2>
</div>

In [4]:
'''
StackOverflow Annual Developer Survey 2020

With nearly 65,000 responses fielded from over 180 countries and dependent territories, our 2020 Annual 
Developer Survey examines all aspects of the developer experience from career satisfaction and job search 
to education and opinions on open-source software.
'''

df = pd.read_csv('../../../all_dfs/developer_survey_2020/survey_results_public.csv', index_col='Respondent')
df.head(3)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN

In [5]:
df_schema = pd.read_csv('../../../all_dfs/developer_survey_2020/survey_results_schema.csv')
df_schema

                Column                                       QuestionText
0           Respondent  Randomized respondent ID number (not in order ...
1           MainBranch  Which of the following options best describes ...
2             Hobbyist                            Do you code as a hobby?
3                  Age  What is your age (in years)? If you prefer not...
4           Age1stCode  At what age did you write your first line of c...
..                 ...                                                ...
56  WebframeWorkedWith  Which web frameworks have you done extensive d...
57       WelcomeChange  Compared to last year, how welcome do you feel...
58         WorkWeekHrs  On average, how many hours per week do you wor...
59           YearsCode  Including any education, how many years have y...
60        YearsCodePro  NOT including education, how many years have y...

[61 rows x 2 columns]

<a id='4.0'></a>
<div class="alert alert-block alert-danger">
<h2>Dataframes to SQL</h2>
</div>

In [6]:
def uniquestosql(df, col):
    # create a dataframe with unique values to send to sql
    df_unique = pd.DataFrame(data=df[col].unique(), columns=[col]).dropna()
    
    # send the dataframe to sql
    # if_exists{â€˜failâ€™, â€˜replaceâ€™, â€˜appendâ€™}, default â€˜failâ€™
    df_unique.to_sql(col, con=engine, if_exists='replace')
    
    # replace the values in the main dataframe with the index of the df_unique
    for unq in df_unique[col]:
        ind = df_unique[(df_unique[col] == unq)].index
        df[col] = df[col].replace(unq, str(ind[0]))
        
    return df

In [7]:
cols = ['MainBranch', 'Hobbyist', 'CompFreq', 'Country', 'CurrencyDesc', 'CurrencySymbol', 'EdLevel',
        'Employment', 'Gender', 'JobSat', 'JobSeek', 'NEWDevOps', 'NEWDevOpsImpt', 'NEWEdImpt', 'NEWLearn',
       'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms', 'NEWOvertime', 'NEWPurpleLink', 'OpSys', 'OrgSize',
       'PurchaseWhat', 'Sexuality', 'SOAccount', 'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase',
       'SurveyLength', 'Trans', 'UndergradMajor', 'WelcomeChange']

for col in cols:
    df = uniquestosql(df, col)

<a id='5.0'></a>
<div class="alert alert-block alert-danger">
<h2>Send the main dataframe replaced with index values</h2>
</div>

In [8]:
pd.set_option('display.max_columns',100)

df.head(3)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,0,0,NaN,13,0,NaN,NaN,0,0,0,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...",0,0,White or of European descent,0,"Languages, frameworks, and other technologies ...",0,0,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,0,0,0,NaN,NaN,0,0,NaN,0,0,Start a free trial;Ask developers I know/work ...,0,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,0,0,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,0,0,0,NaN,0,0,0,0,0,ASP.NET Core,ASP.NET;ASP.NET Core,0,50.0,36,27
2,0,1,NaN,19,NaN,NaN,NaN,1,1,1,NaN,NaN,"Developer, full-stack;Developer, mobile",1,1,NaN,NaN,NaN,1,0,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,0,NaN,NaN,0,0,NaN,0,NaN,NaN,0,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,1,1,iOS;Kubernetes;Linux;MacOS,iOS,1,NaN,1,1,1,0,NaN,NaN,NaN,0,NaN,NaN,1,NaN,7,4
3,1,0,NaN,15,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,2,NaN,NaN,NaN,NaN,NaN,1,2,2,1,0,0,NaN,NaN,NaN,NaN,1,NaN,4,NaN

In [9]:
df.to_sql('main_table', con=engine, if_exists='replace')

<a id='6.0'></a>
<div class="alert alert-block alert-danger">
<h2>Add comments into sql tables</h2>
</div>

In [10]:
# get the table names in the sql
sql = 'SHOW TABLES FROM developer_survey_2020'
df_tables = pd.read_sql_query(sql, engine)
print(df_tables.iloc[:,0].values)

['CompFreq' 'Country' 'CurrencyDesc' 'CurrencySymbol' 'EdLevel'
 'Employment' 'Gender' 'Hobbyist' 'JobSat' 'JobSeek' 'main_table'
 'MainBranch' 'NEWDevOps' 'NEWDevOpsImpt' 'NEWEdImpt' 'NEWLearn'
 'NEWOffTopic' 'NEWOnboardGood' 'NEWOtherComms' 'NEWOvertime'
 'NEWPurpleLink' 'OpSys' 'OrgSize' 'PurchaseWhat' 'Sexuality' 'SOAccount'
 'SOComm' 'SOPartFreq' 'SOVisitFreq' 'SurveyEase' 'SurveyLength' 'Trans'
 'UndergradMajor' 'WelcomeChange']

In [11]:
df_schema_list = list(df_schema["Column"].values)

# get the index number and the description in the QuestionText column by using the table names
for table in df_tables['Tables_in_developer_survey_2020']:
    if table in df_schema_list:
        ind = df_schema[df_schema['Column'] == table].index[0]
        txt = df_schema.loc[ind,'QuestionText']
        txt = txt.replace('"', "'")     # to solve error while "conn.execute(sql)"

        # update the sql tables according to each column description in df_schema
        sql = """
        ALTER TABLE developer_survey_2020.{}
        COMMENT = "{}";
        """.format(table, txt)

        with engine.begin() as conn:
            conn.execute(sql)

<a id='7.0'></a>
<div class="alert alert-block alert-danger">
<h2>Add comments into columns in a sql table</h2>
</div>

In [19]:
# get the column names of the main table in the sql
sql = 'SHOW COLUMNS FROM developer_survey_2020.main_table;'
df_col = pd.read_sql_query(sql, engine)['Field']

for col in df_col:
    # the first column is index.
    if col != 'Respondent':
#         print(col)
        # get the index number and the description in the QuestionText column by using the table column names
        ind = df_schema[df_schema['Column'] ==col].index[0]
        txt = df_schema.loc[ind,'QuestionText']
        txt = txt.replace('"', "'")     # to solve error while "conn.execute(sql)"
        
        sql = """
        ALTER TABLE developer_survey_2020.main_table
        CHANGE COLUMN {} {} TEXT NULL DEFAULT NULL COMMENT "{}";
        """.format(col, col, txt)
            
        try:
            # update the columns according to each column description in df_schema
            sql = """
            ALTER TABLE developer_survey_2020.main_table
            CHANGE COLUMN {} {} TEXT NULL DEFAULT NULL COMMENT '{}';
            """.format(col, col, txt)
            with engine.begin() as conn:
                conn.execute(sql)
        except:
            sql = """
            ALTER TABLE developer_survey_2020.main_table
            CHANGE COLUMN {} {} TEXT NULL DEFAULT NULL COMMENT "{}";
            """.format(col, col, txt)
            with engine.begin() as conn:
                conn.execute(sql)